2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:setup_run_log_directory():647] Logging user logs to .\wandb\run-20250306_111204-m7fyaqvw\logs\debug.log
2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to .\wandb\run-20250306_111204-m7fyaqvw\logs\debug-internal.log
2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D995A17190>
2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:init():761] calling init triggers
2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:init():784] starting backend
2025-03-06 11:12:04,503 INFO    MainThread:39444 [wandb_init.py:init():788] sending inform_init request
2025-03-06 11:12:04,506 INFO    MainThread:39444 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-06 11:12:04,506 INFO    MainThread:39444 [wandb_init.py:init():803] backend started and connected
2025-03-06 11:12:04,510 INFO    MainThread:39444 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-06 11:12:04,510 INFO    MainThread:39444 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-06 11:12:04,510 INFO    MainThread:39444 [wandb_init.py:init():896] updated telemetry
2025-03-06 11:12:04,553 INFO    MainThread:39444 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-06 11:12:05,144 INFO    MainThread:39444 [wandb_init.py:init():995] starting run threads in backend
2025-03-06 11:12:05,327 INFO    MainThread:39444 [wandb_run.py:_console_start():2377] atexit reg
2025-03-06 11:12:05,328 INFO    MainThread:39444 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-06 11:12:05,328 INFO    MainThread:39444 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-06 11:12:05,328 INFO    MainThread:39444 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-06 11:12:05,329 INFO    MainThread:39444 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-06 11:13:52,269 INFO    MainThread:39444 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-06 11:13:52,269 INFO    MainThread:39444 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-06 11:13:52,294 INFO    MainThread:39444 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-06 11:13:52,321 INFO    MainThread:39444 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-06 11:13:52,322 INFO    MainThread:39444 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-06 11:15:09,063 INFO    MainThread:39444 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-06 11:15:09,065 INFO    MainThread:39444 [wandb_run.py:_finish():2112] finishing run maximilien003-universit-de-mons/TP4 MNIST/m7fyaqvw
2025-03-06 11:15:09,065 INFO    MainThread:39444 [jupyter.py:save_history():458] not saving jupyter history
2025-03-06 11:15:09,065 INFO    MainThread:39444 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-06 11:15:09,065 INFO    MainThread:39444 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-06 11:15:09,065 INFO    MainThread:39444 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 0
2025-03-06 11:15:09,066 INFO    MainThread:39444 [wandb_run.py:_restore():2324] restore
2025-03-06 11:15:09,066 INFO    MainThread:39444 [wandb_run.py:_restore():2330] restore done
